[package]
name = "hangman"
version = "0.1.0"
authors = ["wakuto"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
linked_hash_set = "0.1.4"
